name: Unit Test GCBrickWork

on:
  workflow_dispatch:

jobs:
  pytest-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel -r requirements.txt

      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s  

      - name: Generate Coverage Report
        run: |  
          coverage report -m